---

- name: Install Logrotate packages
  package:
    name: '{{ logrotate_packages }}'
    state: present
  become: yes
  tags: packages

- name: Configure Logrotate
  template:
    src: '{{ lograte_config_file }}'
    dest: /etc/logrotate.conf
    mode: '644'
  become: yes
  tags: config
  when: lograte_config_file|length > 0

- name: Setup the log rotations
  template:
    src: '{{ item.config_file }}'
    dest: /etc/logrotate.d/{{ item.name }}
    mode: '644'
    validate: 'logrotate --debug %s'
  become: yes
  loop: '{{ logrotate_log_rotations }}'
  loop_control:
    label: '{{ item.name }}'
  tags: logs
